version: '3'

services:
  django_dns:
    build: .
    environment:
      - IPINFODB_API_KEY=FILL_IN
      - DJANGO_SECRET_KEY=FILL_IN
    ports:
      - 8000:8000
    volumes:
      - .://usr/django_dns/code
      - static_volume:/usr/django_dns/code/dns_cache/static