version: '3'

services:
  django_dns:
    build: .
    environment:
      - IPINFODB_API_KEY=Yo
      - DJANGO_SECRET_KEY=Yo
    ports:
      - 7999:7999
    volumes:
      - .://usr/django_dns/code
      - /django_apps/dns_static/static/:/usr/django_dns/code/dns_cache/staticfiles

networks:
  default:
    external:
      name: postgres_pg_network
